import LocalizedStrings from 'react-localization';

let strings = new LocalizedStrings({

    en: {
        how: "How do you want your egg today?",
        boiledEgg: "Boiled egg",
        softBoiledEgg: "Soft-boiled egg",
        choice: "How to choose the egg",
        msg: "You should get access to this page only after authentication.",
        title: "SBF-Booking System",
        login: "Login",
        logout: "Log out",
        signup: "Sign up",
        createaccount: "Create an account",
        douhaveaccount: "Already have an account?",
        ihaveaccount: "I already have an account",
        email: "E-mail",
        password: "Passsword",
        name: "Full name",
        username: "Username",
        sendBtn: "Send",
        doneBooking: "Your booking was successfull!",
        thankMsg: "Thank you and welcome back!",
        chooseCykel: "Choose a bike to see available period",
        hbgstadTile: "Helsingborg city",
        addperiod: "Add new period",
        removeperiod: "Remove period",
        addbike: "Add new bike",
        removebike: "Delete bike",
        periodname: "t.ex. #1 Period",
        datefrom: "Date from yyyy-mm-dd",
        dateto: "Date to yyyy-mm-dd",
        removeperiod: "Remove period",
        address: "Address",
        city: "City",
        phone: "Phone",
        maintitle: "Booking page bicycle library Helsingborg",
        msgLoginReg: "Register or log in to book a bike",
        addbiketxt: "Add new bike",
        bikenametext: "Bike name",
        biketype: "Bike type",
        removebike: "Remove bike",
        imgurl: "Add image URL",
        book: "Book",
        unbook: "Unbook",
        unbooked: "Unbooked",
        nextyearmsg: "You can book this bike again in the following date : ",
        meromcykel: "More about the bikes",
        tillbakahuvsida: "Go back to the main site",
        bikedescurl: "https://cykelbiblioteket.helsingborg.se/",
        mybook: 'My booking',
        viewallbook: "View all booking",
        viewallusers: "View all users",
        goback: "Go back to booking",
        amount: "Add the amount of bikes",
        adminnote: "Admin kommentar",
        areyousure: "Är du säker på att du vill avboka cykeln?",
        accountregistered: "Thank your for your registration!",
        sorttx: "Sortera",
        confirmlogin: "Confirm and login",
        resetpassword: "Reset password",
        forgotpassword: "Forgot your password?",
        cancelLabel: "Cancel",
        datepickerhint: "Choose date - yyyy-mm-dd"
    },

    sv: {
        how: "Hur vill du har dina ägg?",
        boiledEgg: "Uovo sodo",
        softBoiledEgg: "Uovo alla coque",
        choice: "Come scegliere l'uovo",
        msg: "Du har tillgång till den sida efter inloggning",
        title: "SBF-bokningssystem",
        login: "Logga in",
        logout: "Logga ut",
        signup: "Registrera dig",
        createaccount: "Skapa ett konto",
        douhaveaccount: "Har du inget konto?",
        ihaveaccount: "Jag har redan konto",
        email: "E-post",
        password: "Lösenord",
        name: "Fullständiga namn",
        username: "Användarnamn",
        sendBtn: "BOKA",
        doneBooking: "Din bokning är klar!",
        thankMsg: "Tack för din bokning!",
        chooseCykel: "Välj en cykel för att se tillgänglig period",
        hbgstadTile: "Helsingborg stad",
        addperiod: "Lägg till period",
        removeperiod: "Ta bort period",
        addbike: "Lägga till cykel",
        removebike: "Ta bort cykel",
        periodname: "t.ex. #1 Period",
        datefrom: "Datum från yyyy-mm-dd",
        dateto: "Datum till yyyy-mm-dd",
        removeperiod: "Ta bort period",
        address: "Adress",
        city: "Ort",
        phone: "Telefon",
        maintitle: "Cykelbokningssida",
        msgLoginReg: "Registrera dig eller logga in för att boka cykel",
        addbiketxt: "Lägg till",
        bikenametext: "Cykel name",
        biketype: "Cykel typ",
        removebike: "Ta bort cykel",
        imgurl: "Lägga till bild URL",
        book: "Boka",
        unbook: "Avboka",
        unbooked: "Avbokat",
        nextyearmsg: "Du kan boka den här cykeln igen på följande datum : ",
        meromcykel: "Mer om cyklarna",
        tillbakahuvsida: "Tillbaka till huvudsidan",
        bikedescurl: "https://cykelbiblioteket.helsingborg.se/",
        mybook: 'Mina bokningar',
        viewallbook: "Se alla bokningar",
        viewallusers: "Se alla användare",
        goback: "Tillbaka till bokning",
        amount: "Vänligen ange mängden cyklar",
        adminnote: "Admin kommentar",
        areyousure: "Är du säker på att du vill avboka cykeln?",
        accountregistered: "Tack för din registrering!",
        sorttx: "Sortera",
        confirmlogin: "Bekräfta och logga in",
        resetpassword: "Återställ lösenord",
        forgotpassword: "Glömt ditt lösenord?",
        cancelLabel: "Avbryt",
        datepickerhint: "Välja upphämtningsdatum - yyyy-mm-dd"
    }
});

export default strings;
